name: codespell 
version: 'v1.11.0'
summary: Check code for common misspellings
description: |
  Codespell fixes common mispellings in text files.It's designed 
  primarily for checking misspelled words in source code, but it can 
  be used with other files as well.

grade: stable
confinement: strict

apps:
  codespell:
    command: codespell
    plugs: [home]
    
parts:
  codespell:
    source: https://github.com/lucasdemarchi/codespell.git
    source-tag: v1.11.0
    plugin: python
